openapi: 3.0.3
info:
  title: MS-SQL API
  description: API for a MS SQL server
  version: 1.0.0
tags:
  - name: User
    description: User CRUD

paths:
  /user/create: {$ref: 'paths/users.yaml#/paths/create'}
  /user/login: {$ref: 'paths/users.yaml#/paths/login'}
  /user/loginByToken: {$ref: 'paths/users.yaml#/paths/loginByToken'}
  /user/logout: {$ref: 'paths/users.yaml#/paths/logout'}
  /user/passwordChange: {$ref: 'paths/users.yaml#/paths/changePassword'}
  /user/passwordRecovery: {$ref: 'paths/users.yaml#/paths/recoverPassword'}
  /user/passwordInputToken: {$ref: 'paths/users.yaml#/paths/inputToken'}
  /user/setName: {$ref: 'paths/users.yaml#/paths/setName'}
  /user/getName: {$ref: 'paths/users.yaml#/paths/getName'}
  /user/setGoal: {$ref: 'paths/users.yaml#/paths/setGoal'}
  /user/getGoal: {$ref: 'paths/users.yaml#/paths/getGoal'}
  /user/setWeight: {$ref: 'paths/users.yaml#/paths/setWeight'}
  /user/getWeight: {$ref: 'paths/users.yaml#/paths/getWeight'}
  /user/setHeight: {$ref: 'paths/users.yaml#/paths/setHeight'}
  /user/getHeight: {$ref: 'paths/users.yaml#/paths/getHeight'}
  
  /history/get: {$ref: 'paths/history.yaml#/paths/history-get'}
  /history/add: {$ref: 'paths/history.yaml#/paths/history-add'}
  /history/remove: {$ref: 'paths/history.yaml#/paths/history-remove'}