openapi: 3.0.3
info:
  title: MS-SQL API
  description: API for a MS SQL server
  version: 1.0.0
tags:
  - name: User
    description: User CRUD

paths:
  /user/create: {$ref: 'paths/users.yaml#/paths/create'}
  /user/login: {$ref: 'paths/users.yaml#/paths/login'}
  /user/loginByToken: {$ref: 'paths/users.yaml#/paths/loginByToken'}
  /user/logout: {$ref: 'paths/users.yaml#/paths/logout'}
  /user/passwordChange: {$ref: 'paths/users.yaml#/paths/changePassword'}
  /user/passwordRecovery: {$ref: 'paths/users.yaml#/paths/recoverPassword'}
  /user/passwordInputToken: {$ref: 'paths/users.yaml#/paths/inputToken'}
  
  /history/get: {$ref: 'paths/history.yaml#/paths/history-get'}
  /history/add: {$ref: 'paths/history.yaml#/paths/history-add'}
  /history/remove: {$ref: 'paths/history.yaml#/paths/history-remove'}