openapi: 3.0.3
info:
  title: MS-SQL API
  description: API for a MS SQL server
  version: 1.0.0
tags:
  - name: User
    description: User CRUD
paths:
  /User:
    post:
      tags:
        - User
      summary: Create User
      x-router-controller: users
      operationId: createUser
      requestBody:
        description: Created User object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
  /User/login:
    post:
      tags:
        - User
      summary: Logs User into the system
      x-router-controller: users
      operationId: loginUser
      requestBody:
        description: Created User object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoggin'
      responses:
        '200':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the User
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid Username/password supplied
  /User/{Username}:
    patch:
      tags:
        - User
      summary: Update User
      x-router-controller: users
      operationId: updateUser
      parameters:
        - name: Username
          in: path
          description: name that need to be deleted
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent User in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: successful operation
    delete:
      tags:
        - User
      summary: Delete User
      x-router-controller: users
      operationId: deleteUser
      parameters:
        - name: Username
          in: path
          description: The name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid Username supplied
        '404':
          description: User not found
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          example: MateusBittencourt
        email:
          type: string
          example: mateus.bittencourt@outlook.com
        password:
          type: string
          example: password
    UserLoggin:
      type: object
      properties:
        username:
          type: string
          example: MateusBittencourt
        password:
          type: string
          example: password
  